/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.ImageIcon;

/**
 *
 * @author Ariel
 */
public class Mensaje extends javax.swing.JDialog {

    /**
     * Creates new form Mensaje
     */
    public Mensaje(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        univer = new javax.swing.JLabel();
        facultad = new javax.swing.JLabel();
        mate = new javax.swing.JLabel();
        es1 = new javax.swing.JLabel();
        es2 = new javax.swing.JLabel();
        es3 = new javax.swing.JLabel();
        es4 = new javax.swing.JLabel();
        carrera = new javax.swing.JLabel();
        gest = new javax.swing.JLabel();
        doc = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        es5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Datos");
        setBackground(new java.awt.Color(204, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 400, 400));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoFcyt.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(320, 10, 70, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoUmss.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 20, 70, 80);

        univer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        univer.setText("Universiad Mayor de San Simón");
        getContentPane().add(univer);
        univer.setBounds(100, 20, 190, 14);

        facultad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        facultad.setText("Facultad de ciencias y tecnología");
        getContentPane().add(facultad);
        facultad.setBounds(100, 40, 190, 14);

        mate.setText("Materia:            Inteligencia Artificial");
        getContentPane().add(mate);
        mate.setBounds(100, 90, 220, 14);

        es1.setText("Estudiantes:   Adriazola Muriel David");
        getContentPane().add(es1);
        es1.setBounds(100, 110, 230, 14);

        es2.setText("   Galvez Ponce Ariel");
        getContentPane().add(es2);
        es2.setBounds(170, 130, 140, 14);
        getContentPane().add(es3);
        es3.setBounds(230, 230, 150, 14);

        es4.setText("   Villazon Delgado Gabriel");
        getContentPane().add(es4);
        es4.setBounds(170, 170, 160, 14);

        carrera.setText("Carrera:            Ingenieria de Sistemas");
        getContentPane().add(carrera);
        carrera.setBounds(100, 190, 230, 14);

        gest.setText("Gestión:            I/2015");
        getContentPane().add(gest);
        gest.setBounds(100, 230, 150, 14);

        doc.setText("Docente:           Lic. Garcia Perez Carmen Rosa");
        getContentPane().add(doc);
        doc.setBounds(100, 210, 270, 14);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar);
        btnAceptar.setBounds(170, 270, 80, 23);

        es5.setText("Rocha Vargas Carola");
        getContentPane().add(es5);
        es5.setBounds(180, 150, 160, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnAceptarActionPerformed
    public void ver(){
        Mensaje dialog = new Mensaje(new javax.swing.JFrame(), true);
                dialog.setSize(420,350);
                dialog.setLocationRelativeTo(null);
                dialog.setIconImage(new ImageIcon("src/imagenes/icono2.png").getImage());
                //dialog.setBackground(Color.yellow);
                
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        //Mensaje.EXIT_ON_CLOSE(0);
                    }
                });
                dialog.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel carrera;
    private javax.swing.JLabel doc;
    private javax.swing.JLabel es1;
    private javax.swing.JLabel es2;
    private javax.swing.JLabel es3;
    private javax.swing.JLabel es4;
    private javax.swing.JLabel es5;
    private javax.swing.JLabel facultad;
    private javax.swing.JLabel gest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel mate;
    private javax.swing.JLabel univer;
    // End of variables declaration//GEN-END:variables
}
